site_name: 个人学习 Wiki
site_url: https://DualPhaseDev.github.io/wiki
repo_url: https://github.com/DualPhaseDev/wiki
repo_name: DualPhaseDev/wiki
edit_uri: edit/main/docs/

theme:
  name: material
  language: zh
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/weather-night
        name: 暗黑模式
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/weather-sunny
        name: 浅色模式
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.top
    - navigation.indexes
    - search.suggest
    - search.highlight
    - content.code.copy

plugins:
  - search

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.emoji
  - pymdownx.tabbed
  - toc:
      permalink: true

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/DualPhaseDev

copyright: Copyright &copy; 2026 DualPhaseDev
